global:
  #smtp_from: p4miscjp@gmail.com
  #smtp_smarthost: localhost:25
  #smtp_require_tls: false
  # Hello is the local machine name
  #   smtp_hello: p4hms
  #
  #   route:
  #     group_by: ['alertname']
  #       group_wait: 30s
  #         group_interval: 5m
  #           repeat_interval: 60m
  #             receiver: mail
  #
  #             receivers:
  #             - name: mail
  #               email_configs:
  #                 - to: p4-group@perforce.com
