version: '3'

services:
  centos7upd:
    build: ./centos7upd
    image: centos7upd
    container_name: centos7upd

  helix:
    build: .
    image: helix
    container_name: helix
    ports:
      - 1666:1666
