FROM centos:7
LABEL maintainer "p4misc <p4miscjp@gmail.com>"
RUN yum -y update
RUN yum install -y which \
                   wget \
                   zlib \
                   zlib-devel \
                   openssl \
                   openssl-devel \
                   gcc \
                   gcc-c++
